drop sequence if exists seq_pericias_no_armas; 

CREATE SEQUENCE seq_pericias_no_armas
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

drop table if exists pericias_no_armas;

create table pericias_no_armas(id int primary key,
nombre varchar2(100),
casillas_requeridas int,
habilidad varchar2(25),
modificador int default 0,
id_categoria int );


insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Agricultura','1','Inteligencia','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Albañilería','1','Fuerza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Alfarería','1','Destreza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Bailar','1','Destreza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Cabalgar por el aire','2','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Cabalgar por el suelo','1','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Cantar','1','Carisma','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Carpintería','1','Fuerza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Cocinar','1','Inteligencia','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Destilación','1','Inteligencia','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Encender fuego','1','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Entrenamiento de animales','1','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Etiqueta','1','Carisma','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Habilidad artística','1','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Heráldica','1','Inteligencia','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Herrería','1','Fuerza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Lenguajes modernos','1','Inteligencia','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Manejo de animales','1','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Mareaje','1','Destreza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Minería','2','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Modisto / Sastre','1','Destreza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Nadar','1','Fuerza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Pescar','1','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Sentido de la dirección','1','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Sentido del clima','1','Sabiduría','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Tejer','1','Inteligencia','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Trabajo del cuero','1','Inteligencia','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Uso de la cuerda','1','Destreza','0','0');
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Zapatero remendón','1','Destreza','0','0');

insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Acrobacia','1','Destreza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Caminar por la cuerda floja','1','Destreza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Disfraz','1','Carisma','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Falsificación','1','Destreza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia antigua','1','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia local','1','Carisma','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Instrumentos musicales','1','Destreza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Juego','1','Carisma','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Leer los labios','2','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Luchar a ciegas','2','NN','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Malabarismos','1','Destreza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Montar trampas','1','Destreza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Saltar','1','Fuerza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Tallado de gemas','2','Destreza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Tasación/Evaluación','1','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Ventriloquia','1','Inteligencia','0',(select id from categoria where nombre='ladron'));

insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Acrobacia','1','Destreza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Caminar por la cuerda floja','1','Destreza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Disfraz','1','Carisma','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Falsificación','1','Destreza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia antigua','1','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia local','1','Carisma','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Instrumentos musicales','1','Destreza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Juego','1','Carisma','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Leer los labios','2','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Luchar a ciegas','2','NN','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Malabarismos','1','Destreza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Montar trampas','1','Destreza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Saltar','1','Fuerza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Tallado de gemas','2','Destreza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Tasación/Evaluación','1','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Ventriloquia','1','Inteligencia','0',(select id from categoria where nombre='bardo'));


insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Astrología','0','Inteligencia','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Herbalismo','-2','Inteligencia','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia antigua','-1','Inteligencia','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Identificar conjuros','-2','Inteligencia','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Ingeniería','-3','Inteligencia','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Leer/Escribir','1','Inteligencia','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Lenguajes antiguos','0','Inteligencia','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Navegación','-2','Inteligencia','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Religión','0','Sabiduría','0',(select id from categoria where nombre='mago'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Talla de gemas','-2','Destreza','0',(select id from categoria where nombre='mago'));

insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Armero','-2','Inteligencia','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Arquero/Flechero','-1','Destreza','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Caza','-1','Sabiduría','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Comprensión de animales','0','Inteligencia','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Conducir carros','2','Destreza','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Correr','-6','Constitución','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Forja de armas','-3','Inteligencia','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Juego','0','Carisma','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Luchar a ciegas','NN','NN','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Montañismo','NN','NN','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Montar trampas','-1','Destreza','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Navegación','-2','Inteligencia','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Rastreo','0','Sabiduría','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Resistencia','0','Constitución','0',(select id from categoria where nombre='guerrero'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Supervivencia','0','Inteligencia','0',(select id from categoria where nombre='guerrero'));


insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Armero','-2','Inteligencia','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Arquero/Flechero','-1','Destreza','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Caza','-1','Sabiduría','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Comprensión de animales','0','Inteligencia','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Conducir carros','2','Destreza','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Correr','-6','Constitución','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Forja de armas','-3','Inteligencia','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Juego','0','Carisma','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Luchar a ciegas','NN','NN','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Montañismo','NN','NN','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Montar trampas','-1','Destreza','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Navegación','-2','Inteligencia','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Rastreo','0','Sabiduría','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Resistencia','0','Constitución','0',(select id from categoria where nombre='paladin'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Supervivencia','0','Inteligencia','0',(select id from categoria where nombre='paladin'));


insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Armero','-2','Inteligencia','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Arquero/Flechero','-1','Destreza','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Caza','-1','Sabiduría','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Comprensión de animales','0','Inteligencia','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Conducir carros','2','Destreza','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Correr','-6','Constitución','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Forja de armas','-3','Inteligencia','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Juego','0','Carisma','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Luchar a ciegas','NN','NN','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Montañismo','NN','NN','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Montar trampas','-1','Destreza','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Navegación','-2','Inteligencia','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Rastreo','0','Sabiduría','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Resistencia','0','Constitución','0',(select id from categoria where nombre='guardabosques'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Supervivencia','0','Inteligencia','0',(select id from categoria where nombre='guardabosques'));

insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Astrología','0','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Curación','-2','Sabiduría','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Herbalismo','-2','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia antigua','-1','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia local','0','Carisma','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Identificar conjuros','-2','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Ingeniería','-3','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Instrumentos musicales','-1','Destreza','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Leer/Escribir','1','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Lenguajes antiguos','0','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Navegación','-2','Inteligencia','0',(select id from categoria where nombre='ladron'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Religión','0','Sabiduría','0',(select id from categoria where nombre='ladron'));


insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Astrología','0','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Curación','-2','Sabiduría','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Herbalismo','-2','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia antigua','-1','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Historia local','0','Carisma','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Identificar conjuros','-2','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Ingeniería','-3','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Instrumentos musicales','-1','Destreza','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Leer/Escribir','1','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Lenguajes antiguos','0','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Navegación','-2','Inteligencia','0',(select id from categoria where nombre='bardo'));
insert into pericias_no_armas (id, nombre, casillas_requeridas, habilidad, modificador, id_categoria)  values  ((select next value for seq_pericias_no_armas from dual),'Religión','0','Sabiduría','0',(select id from categoria where nombre='bardo'));

